language: node_js
node_js:
- '0.11'
- '5.0'
- '6.0'
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: d1E4NgktRTQpxJUrOdEEx2ueVF9OY8AhNs2fiAsIx9xgHykLrwa7Z/zK3UaW6X8ia9sQS6+i6JQF6qLD1F5i/G/PrKof95n5pa6Basygg59vqJ+lu3QpD/9bGngkZ/c/AGOjjT1Q2QYKoXWQgNj7sNwxnj7jhB6RrlzSsCuHy3R+Ve2lcRromyq1WvkWzcrzKsoEfrh63aEh5RuhJxW0+tcGa9G0rqPucBcs54U9rF00pd2MduXelylJBUZBeiydJCO8kB3p3aQFRTtvqMocsQgOqIQrOtLH64hgfZzIyf/ppWcyQAD3tRTd0KTggNLGYspKWwhVHb/lAIllpE20wsQpRI2uJoEfzBTEobkTCtMWjY93kGWLQjS3ickcNk6Sf/MrNVeaCvBty5NFJ6R2oCpcLRt5OKwZIbfTBHcrH6p/hfDRThYet/KALPZdwB4MFpjTX5/uBpKa5nfml7Tu/+eU7nCHowW1XOZq69KGJ3PaHMTkbKHb58yq4buw4VcbeqKnZwI/sMqV3U9ZasrJ6rfdki+MEzdFayYcFhtPzzHw7OchDj9IVhF1B938G9/MfCmRH/ss6wYYf8y2rSSFTEwLq94zV4cO5qFl5ohu8+AbRQFgYt3EboJGoHQwTXq1Gd3ks4HPE+7TwfUNBFyrcd0nsiCbDLAvq6Po4Ouc+YQ=
    on:
      tags: true
      node: '5.0'
  - provider: releases
    api_key:
      secure: cSCQnjrAwsI4G/z40uE0nLHqiepZW4yguLsDBFUhGHmnl9RCmT9Hax7dEYE/WAN1Fw7gdnpDxDzXh9SsTF4f56/UmSyCjbr9EkpX//E08rrHDbqUNsNalBasmq3UdxGnP/mQBGQXLEntofmiMtAtMZpSBFlS5tAGfoB/f4L6V0KPivV3wv1+lDmt6uqsJIoivB1sGaCCbjbA8pK4tDwW4pcSFtEmnnnpzl6S6fgCu6Scd849YEVb3+diLuFG7f8aDZLjb7gvXJroI6VKKdYa4cVC70WMa+cSn5BZ59XrI5y2zOX5uIfJSSBx2fz+8Ji3F2Tyd12BgFtRJEpZTiP2SC8YS1SzM/28QgnpgytYfwk6id5JCRoTLVv6QOAMU1bk9wiq2YpFQK5JLrT8sZqBFNlXmi8mfNKZQyAkFGMsL1aNIAH5wG6GFdJwb8Tnglndnct+jScNxVy9A/5rdSHrSCTz7KwN72aJQ333idKO83nR/PghaTecEryQrcsUmKtIwc7XH344DkqXrImimQktgVNoT2kJlMfzC8pLtDgUuz/iAMgxwuFyVcy6dQuDxFNuH5dsrSbqTFE0C0HDzoVLxBULltxe0sI1zeXa1KY4fgJRaHwbjwCfbs9jVQrN7mPl/zyozX4ZnpV+JTzB+mwBf2pS/tOBRY82KWZNfboCXxE=
    file:
      - "character-entities-html4.js"
      - "character-entities-html4.min.js"
    on:
      tags: true
      node: '6.0'
