language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bAbjX7kckupCQPkmFExW/73NqQlWrP+sAZ36N83yOWWog1x/lQfIeyrHLh0ui5kS/u+jPAkz/ZJv5v2qrHJ/jezoKB6dpYdw3RLr2vksHdwuAnRm9nsykN4PR4iyusKws7IyNpddGp9UROL0xjrr6zs+PNJ8O1jODr7G1g65v8DS6ZbcL0ZMiiyx4QwqF5BZHg6IgYTjtA8tgzm04D38KhBB34RY4jK/WPmHCgAqGaBgclR+ko+usxUfKgeI9qjE1Lh3sgnjNscp+7jvTLTN7/ANAM4vdc2EW9BhTQ1XuCqzSEY8ZlBdRNr/3Vm9ncsVFry6fcLRnX1QRicdSSU/d+iOuQa9IlWxC7iNGvfMSTiCCFlzV1BkWwt22V0Y0SN8YCMwM2MvMN3FY1kBhiJ2mIzCyyLxJk5l1lf7ZrgIeHAjM79dIWtSs7JAWbldTT3fxOJ9D0VZAFRV1imTpIQZ8YeNd/wuimYECfpyP7iczlDu19grb+K6gY5grexfEEu3Z0RtRg9jhgpxzwz0vJzlWDB8OZkdYHfKcpIA8TetU/mHLJ712Bmb7UKKzFA/m5Qs8JRtQk+R07ZLkfmlqnrxhxwXK6cYn+gk6a5ScC0Olpi/QyKz3d4CQ0qhk5ezXCfYi4UdiO0Mq49HQsa4wwe973P9krq+IjSoS9OkxUG7sjc=
  file:
    - 'character-entities-html4.js'
    - 'character-entities-html4.min.js'
  on:
    tags: true
